---
on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      envPAT:
        required: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Run helm lint
        run: 'echo "start helm linting"'
